arrowParens: avoid
bracketSpacing: true
endOfLine: auto
jsxBracketSameLine: false
printWidth: 120
proseWrap: preserve
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: none
