#!/bin/bash

echo //registry.npmjs.org/:_authToken=\${NPM_TOKEN} > ~/.npmrc

cp CHANGELOG.md packages/component
cp README.md packages/component
cp LICENSE packages/component

# If TRAVIS_TAG is present, it means this is going PRODUCTION
if [ -n "$TRAVIS_TAG" ]
then
  cd packages/component
  npm publish
fi

# If on "master" branch, deploy to "master" tag
if [ "$TRAVIS_BRANCH" = "master" ]
then
  cd packages/component
  npm publish --tag master
fi
